[versions]
agp = "8.13.0"
# for koin/ksp support
kotlin = "2.1.21"
ksp = "2.1.21-2.0.2"
coilCompose = "3.3.0"
coilNetworkOkhttp = "3.3.0"
datastorePreferences = "1.1.7"
# kermit compatibility with kotlin lower then 2.2.0
kermit = "2.0.3"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
lifecycleViewmodelCompose = "2.9.4"
media3Exoplayer = "1.8.0"
runner = "1.7.0"
core = "1.7.0"
kotlinxSerializationJson = "1.9.0"
material = "1.13.0"
navigationCompose = "2.9.5"
composeMultiplatform = "1.9.0"
koin = "4.1.1"
koinAnnotations = "2.2.0"
coreKtx = "1.17.0"

[libraries]
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-media3-common-ktx = { module = "androidx.media3:media3-common-ktx", version.ref = "media3Exoplayer" }
androidx-media3-datasource = { module = "androidx.media3:media3-datasource", version.ref = "media3Exoplayer" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilNetworkOkhttp" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
androidx-core = { group = "androidx.test", name = "core", version.ref = "core" }
koin-core = {module = "io.insert-koin:koin-core", version.ref = "koin"}
koin-annotations = {module = "io.insert-koin:koin-annotations", version.ref = "koinAnnotations"}
koin-ksp-compiler = {module = "io.insert-koin:koin-ksp-compiler", version.ref = "koinAnnotations"}
koin-compose-viewmodel-nav = {module = "io.insert-koin:koin-compose-viewmodel-navigation", version.ref = "koin"}
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
